FROM ernestwambua/oces-compilers:focal

ENV VIRTUAL_ENV=/opt/env

ENV FLASK_APP routes.py

ENV FLASK_ENV=development

WORKDIR /app

COPY ./requirements.txt .

RUN set -xe && \
    python3 -m venv $VIRTUAL_ENV && \
    . $VIRTUAL_ENV/bin/activate

RUN $VIRTUAL_ENV/bin/pip3 install -r requirements.txt

COPY ./ ./

EXPOSE 8000

ENTRYPOINT $VIRTUAL_ENV/bin/python3 -m flask run --host=0.0.0.0 --port=8000